flaskaap/books/routes.py
from sqlalchemy import or_
from flask_login import login_required
from flask import (render_template, redirect,
                   request, url_for, flash, Blueprint)

from flaskaap import db
from .models import Book
from flaskaap.users.user_helper import UserHelper
from .forms import BookStoreForm

books_app = Blueprint('books_app', __name__)


@books_app.route('/book_store', methods=['GET', 'POST'])
def book_store():
    page = request.args.get('page', 1, type=int)
    books_per_page = 10
    form = BookStoreForm()
    books = Book.query.paginate(page=page, per_page=books_per_page)
    if request.method == 'GET':
        return render_template('book_store.html', form=form, books=books)
    elif request.method == 'POST':
        if request.form.get("search"):
            t = form.title.data
            search_by = form.search_by.data
            if not t or len(t.strip()) == 0 or search_by.strip() == '0':
                flash("We cannot find out what you want to search! Please Try again")
                return redirect(url_for('books_app.book_store'))
            else:
                search_result = []
                if search_by == 'title':
                    search_result = Book.query.filter(Book.title.ilike(f'%{t}%')).\
                        paginate(page=page, per_page=books_per_page)
                elif search_by == 'author':
                    search_result = Book.query.filter(Book.author.ilike(f'%{t}%')).\
                        paginate(page=page, per_page=books_per_page)
                elif search_by == 'year':
                    search_result = Book.query.filter_by(year=t).\
                        paginate(page=page, per_page=books_per_page)
                elif search_by == 'isbn':
                    search_result = Book.query.filter_by(isbn=t).\
                        paginate(page=page, per_page=books_per_page)

                return render_template("book_store.html", form=form, books=search_result)

        return render_template("book_store.html", form=form, books=books)


@books_app.route('/book_admin', methods=['GET', 'POST'])
@login_required
@UserHelper.is_admin
def book_admin():
    page = request.args.get('page', 1, type=int)
    books_per_page = request.form.get('books_per_page', 10, type=int)
    books = Book.query.paginate(page=page, per_page=books_per_page)
    form = BookStoreForm()
    if request.form.get('edit'):
        book_id = request.form.get('edit')
        book = Book.query.get(book_id)
        form = BookStoreForm(book_id=book.book_id, title=book.title,
                             author=book.author, year=book.year, isbn=book.isbn)
    elif request.form.get('delete'):
        book_id = request.form.get('delete')
        delete_book = Book.query.get_or_404(book_id)
        db.session.delete(delete_book)
        db.session.commit()
        books = Book.query.paginate(page=page, per_page=books_per_page)
        flash("Book Deleted from the database!")
    elif request.form.get("add_new"):
        if form.validate_on_submit():
            t = form.title.data
            a = form.author.data
            y = form.year.data
            i = form.isbn.data
            book = Book(title_=t, author_=a, year_=y, isbn_=i)
            db.session.add(book)
            db.session.commit()
            flash("Book Added to the database!")
    elif request.form.get('update'):
        if form.validate_on_submit():
            update_book = Book.query.get(form.book_id.data)
            update_book.title = form.title.data
            update_book.author = form.author.data
            update_book.year = form.year.data
            update_book.isbn = form.isbn.data
            db.session.commit()
            flash('Book Updated')
    elif request.form.get('search'):
        # TODO let user search for multiple parameters in the
        #  same field e.g. Year= 2005, 2009, Author = Dietal, Kristian
        t = form.title.data
        a = form.author.data
        y = form.year.data
        i = form.isbn.data
        filter_by_expression = []
        if t and len(t.strip()) > 0:
            title_filter = (getattr(Book, 'title').ilike("%%%s%%" % t))
            filter_by_expression.append(title_filter)
        if a and len(a.strip()) > 0:
            author_filter = (getattr(Book, 'author').ilike("%%%s%%" % a))
            filter_by_expression.append(author_filter)
        if y and str(y).isnumeric():
            year_filter = (getattr(Book, 'year') == y)
            filter_by_expression.append(year_filter)
        if i and len(i) > 0:
            isbn_filter = (getattr(Book, 'isbn').ilike("%%%s%%" % i))
            filter_by_expression.append(isbn_filter)
        if len(filter_by_expression) > 0:
            print(filter_by_expression)
            books = db.session.query(Book).filter(or_(*filter_by_expression)).\
                paginate(page=page, per_page=books_per_page)
        else:
            flash("We cannot find out what you want to search! Please Try again")
    elif request.form.get('clear'):
        form = BookStoreForm(None)
    return render_template('book_admin_2.html', books=books, form=form)


@books_app.route('/edit_book',  methods=['GET', 'POST'])
@login_required
def edit_book():
    # TODO make a check that a specific user cannot add more
    #  then 5 books in a day. Only with the book_store_manager
    #  role or admin
    form = BookStoreForm()
    if request.method == 'POST':
        if request.form.get("delete"):
            flash('Please go to the book admin section to delete books!')
            pass
        elif request.form.get("add_new"):
            if form.validate_on_submit():
                t = form.title.data
                a = form.author.data
                y = form.year.data
                i = form.isbn.data
                book = Book(title_=t, author_=a, year_=y, isbn_=i)
                db.session.add(book)
                db.session.commit()
                flash("Book Added to the database!")
        elif request.form.get("view_all"):
            return redirect(url_for('books_app.book_store'))
        elif request.form.get('update'):
            flash('Please go to the book admin section to update books!')
            pass
    return render_template('book_admin.html', form=form)

flaskaap/height_collector/routes.py
from flask import Blueprint, redirect, request, render_template, url_for

from flaskaap import db
from .forms import HeightDataForm
from .models import Height_Data
from .email_sender import EmailSender

height_collector = Blueprint('height_collector', __name__)


@height_collector.route('/height', methods=['GET', 'POST'])
def height_data():
    form = HeightDataForm()
    if request.method == 'GET':
        return render_template('height.html', form=form)
    elif request.method == 'POST':
        if form.validate_on_submit():
            n = form.name.data
            e = form.email.data
            h = form.height.data
            if db.session.query(Height_Data).filter(Height_Data.email_ == e).count() == 0:
                data = Height_Data(name=n, email=e, height=h)
                db.session.add(data)
                db.session.commit()
                EmailSender().send_height_data_email(name=n, email=e, height=h)
                return redirect(url_for('height_collector.height'))
            else:
                # TODO make the error disappear after 20 seconds
                error = "It seems this email is already used"
                return render_template('height.html', form=form, error_message=error)
        return render_template('height.html', form=form)

flaskaap/main/routes.py
from flask import Blueprint, render_template, url_for

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    image_file = url_for('static', filename='images/cc9da77274fe3f5111.png')
    return render_template("home.html", image_file=image_file)


@main.route('/about')
def about():
    return render_template("about.html")


@main.route('/contact')
def contact():
    return render_template("contact.html")


@main.route('/projects')
def projects():
    return render_template("projects.html")

flaskaap/users/routes.py
from datetime import datetime
from flask import (render_template, redirect,
                   request, url_for, flash, Blueprint)
from flask_login import (current_user, login_user,
                         logout_user, login_required)
from flaskaap import db, bcrypt
from .models import User
from .image_helper import (save_user_image,
                           identical_images, delete_image)
from .forms import (RegisterNewUserForm, LoginForm,
                    UpdateAccountForm, ResetPasswordForm,
                    RequestPasswordResetForm)
from .user_helper import UserHelper

users = Blueprint('users', __name__)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        try:
            # Check if data is not changed and the image is
            #  also the same then do not change anything
            if not UserHelper().user_updated(form=form):
                flash("User is not updated because nothing has changed!")
                return redirect(url_for('users.account'))
            # if the user has updated the image check validity
            if form.image.data:
                if not form.image.data.filename == '' and not identical_images(form.image.data):
                    picture_url = save_user_image(form.image.data)
                    # if a new image is saved, delete the previous one
                    if current_user.image_url:
                        delete_image(current_user.image_url)
                    current_user.image_url = picture_url
            current_user.name = form.name.data
            current_user.email = form.email.data
            current_user.username = form.username.data
            current_user.last_updated = datetime.now()
            db.session.commit()
            flash('Account Updated!', 'success')
            return redirect(url_for('users.account'))
        except TypeError as error:
            return render_template('user_account.html', form=form, error_message=error)
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = None
    if current_user.image_url:
        image_file = url_for('static', filename='images/' + current_user.image_url)
    return render_template('user_account.html', form=form, image_file=image_file)


@users.route('/register_new_user', methods=['GET', 'POST'])
def register_new_user():
    if current_user.is_authenticated:
        flash('Please logout to register as a new user')
        return redirect(request.referrer)
    form = RegisterNewUserForm()
    if request.method == 'GET':
        return render_template('register.html', form=form)
    if request.method == 'POST':
        if form.validate_on_submit():
            n = form.name.data
            e = form.email.data
            u = form.username.data
            p = form.password.data
            try:
                image_url = save_user_image(form.image.data)
                hashed_password = bcrypt.generate_password_hash(p).decode('utf-8')
                data = User(name_=n, email_=e, username_=u,
                            password_=hashed_password, image_url_=image_url)
                db.session.add(data)
                db.session.commit()
            except TypeError as error:
                return render_template('register.html', form=form, error_message=error)
            # TODO display a message for 5 sec
            flash("User Created")
            return redirect(url_for('main.home'))
        else:
            return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged-in')
        return redirect(request.referrer)
    form = LoginForm()
    if request.method == 'GET':
        return render_template('login.html', form=form)
    elif request.method == 'POST':
        if form.validate_on_submit():
            user_to_login = User.query.filter_by(username=form.username.data).first()
            if user_to_login and bcrypt.check_password_hash(user_to_login.password, form.password.data):
                login_user(user_to_login, remember=form.remember_me.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                error = 'Please check your username and password and try again'
                return render_template('login.html', form=form, error_message=error)
        return render_template('login.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/request_password_reset', methods=['GET', 'POST'])
def request_password_reset():
    if current_user.is_authenticated:
        flash("Please logout and then try to reset the password")
        return redirect(request.referrer)
    form = RequestPasswordResetForm()
    if form.validate_on_submit():
        reset_pwd_user = User.query.filter_by(email=form.email.data).first()
        UserHelper.send_password_reset_email(user=reset_pwd_user)
        return redirect(url_for('users.login'))
    return render_template("reset_password_request.html", form=form)


@users.route('/reset_password<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        flash("Please logout and then try to reset the password")
        return redirect(request.referrer)
    reset_user_pwd = User.verify_reset_token(token=token)
    if not reset_user_pwd:
        flash("Sorry your token is invalid or expired!")
        return redirect(url_for('users.reset_password'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        reset_user_pwd.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('main.login'))
    return render_template("reset_password.html", form=form)

flaskaap/templates/about.html
{%extends "main_page.html"%}
{%block content%}
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<div class="about">
    <h1>About me</h1>
    <p>Hej!</p>
    <p>
        Welcome to my portfolio. My Name is Faisal Akhlaq. I am living in Copenhagen. <br>
        I am a software developer who loves travelling, fitness activities and sports.<br>
    </p>
    <p>
        Currently I am focused on learning python. As python is a very broadly used <br>
        language, therefore, I learnt basics in different areas.
        <ul>
            <li>Desktop application using tkinter</li>
            <li>Interacting with databases in desktop and web applications <br>
                using SQLAlchemy and simple Database querying. CRUD operations</li>
            <li>Learning bit of mapping</li>
            <li>Graphs using Bokeh and pandas</li>
            <li>Some interesting web-scrapping of static a dynamic websites <br>
                using requests and selenium</li>
            <li>A bit of image and video processing using OpenCV</li>
            <li>Basics of stock market data fetching Candlestick chart</li>
            <li>Deployment of Heroku</li>
            <li>Web apps using Flask, Jinja templating, login management, <br>
                decorators, restricting access to functions and resources<br>
                based on roles</li>
            <li>Web development using Django</li>
        </ul>
    </p>
    <p>
        The software development journey includes many hours of siting in front of a <br>
        computer, stackoverflow, bit of blogging and also going to university for a master <br>
        degree in software engineering and management. The degree part was very  <br>
        interesting and ended happily with two IEEE publication.
    </p>
</div>
{%endblock%}

flaskaap/templates/book_admin.html
{%extends "main_page.html"%}
{%block content%}
<div class="book-admin-page">
    <h1>Book Admin</h1>
    <div class="error-message">
            {{ error_message | safe }}
    </div>
    <form method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}
            {{ form.title(size=30) }}
            {% for error in form.title.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.author.label }}
            {{ form.author(size=30) }}
            {% for error in form.author.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.year.label }}
            {{ form.year(size=30) }}
            {% for error in form.year.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.isbn.label }}
            {{ form.isbn(size=30) }}
            {% for error in form.isbn.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.clear() }}
            {{ form.add_new() }}
            {{ form.search() }}
            {{ form.update() }}
            {{ form.delete() }}
            {{ form.view_all() }}
        </p>
    </form>
</div>
{% endblock %}

flaskaap/templates/book_admin_2.html
{%extends "main_page.html"%}
{%block content%}
<style>
tr:nth-child(odd) { background-color : #EAF2D3; }
tr:hover { background-color : #89ae37; }
overflow-y:scroll;
height:50px;
display:block;
</style>
<div class="book-admin-page">
    <h1>Admin Book Store</h1>
</div>
<div class="book-admin-page">
        <div class="error-message">
            {{ error_message | safe }}
    </div>
    <form method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.book_id(type='hidden') }}
            {{ form.title.label }}
            {{ form.title(size=30) }}
            {% for error in form.title.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.author.label }}
            {{ form.author(size=30) }}
            {% for error in form.author.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.year.label }}
            {{ form.year(size=30) }}
            {% for error in form.year.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.isbn.label }}
            {{ form.isbn(size=30) }}
            {% for error in form.isbn.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.clear() }}
            {{ form.add_new() }}
            {{ form.search() }}
            {{ form.update() }}
            {{ form.view_all() }}
        </p>
    </form>
</div>
<div class="books-table">
    <form method="POST">
        {{ form.hidden_tag() }}
        <label for books_per_page>Books Per Page</label>
        <input id="books_per_page" size="1">
        <table style="width:100%">
              <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Year</th>
                <th>ISBN</th>
                <th book-admin-edit-btn-col>Edit</th>
                <th>Delete</th>
              </tr>
             {% for book in books.items %}
                <tr>
                    <td>{% if book.title %}{{ book.title }} {% endif %}</td>
                    <td>{% if book.author %}{{ book.author }} {% endif %}</td>
                    <td>{% if book.year %}{{ book.year }} {% else %}{{ None }}{% endif %}</td>
                    <td>{% if book.isbn %}{{ book.isbn }} {% else %}{{ None }}{% endif %}</td>
                    <td><button type="submit" name="edit" value="{{ book.book_id }}"
                                formmethod="post" onclick="">Edit</button></td>
                    <td><button type="submit" name="delete" value="{{ book.book_id }}"
                                formmethod="post" onclick="">Delete</button></td>
                </tr>
             {% endfor %}
        </table>

    {% for page_num in books.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if books.page == page_num %}
          <a class="" href="{{ url_for('books_app.book_admin', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="" href="{{ url_for('books_app.book_admin', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
        {% else %}
         ...
        {% endif %}
    {% endfor %}

    <ul class="pagination">
        {% if books.has_prev %}
          <div class="page-item"> <a class="page-link" href="{{ url_for('books_app.book_admin', page=books.prev_num) }}">Previous</a></div>
        {% else %}
          <div class="page-item"><a class="page-link btn disabled" href="#">Previous</a></div>
        {% endif %}
        {% if books.has_next %}
          <div class="page-item"> <a class="page-link" href="{{ url_for('books_app.book_admin', page=books.next_num) }}">Next</a></div>
        {% else %}
          <div class="page-item"><a class="page-link btn disabled" href="#">Next</a></div>
        {% endif %}
    </ul>



    </form>
</div>
{% endblock %}

flaskaap/templates/book_store.html
{%extends "main_page.html"%}
{%block content%}
<div class="book-store-page">
    <h1>Book Store</h1>
    <div class="error-message">
            {{ error_message | safe }}
    </div>
    <form method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{form.search_by.label}}
            {{form.search_by}}
            {{ form.title(size=20) }}<br>
            {{ form.search() }}
            {% for error in form.title.errors %}<br>-->
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            {{ form.view_all() }}
        </p>
    </form>
</div>
<div class="books-table">
    <form method="POST">
        {{ form.hidden_tag() }}
        <table style="width:100%">
              <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Year</th>
                <th>ISBN</th>
                <th book-admin-edit-btn-col>Edit</th>
                <th>Delete</th>
              </tr>
             {% for book in books.items %}
                <tr>
                    <td>{% if book.title %}{{ book.title }} {% endif %}</td>
                    <td>{% if book.author %}{{ book.author }} {% endif %}</td>
                    <td>{% if book.year %}{{ book.year }} {% else %}{{ None }}{% endif %}</td>
                    <td>{% if book.isbn %}{{ book.isbn }} {% else %}{{ None }}{% endif %}</td>
                    <td><button type="submit" name="edit" value="{{ book.book_id }}"
                                formmethod="post" onclick="">Edit</button></td>
                    <td><button type="submit" name="delete" value="{{ book.book_id }}"
                                formmethod="post" onclick="">Delete</button></td>
                </tr>
             {% endfor %}
        </table>



    {% for page_num in books.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if books.page == page_num %}
          <a class="" href="{{ url_for('books_app.book_store', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="" href="{{ url_for('books_app.book_store', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
        {% else %}
         ...
        {% endif %}
    {% endfor %}



    <ul class="pagination">
        {% if books.has_prev %}
          <div class="page-item"> <a class="page-link" href="{{ url_for('books_app.book_store', page=books.prev_num) }}">Previous</a></div>
        {% else %}
          <div class="page-item"><a class="page-link btn disabled" href="#">Previous</a></div>
        {% endif %}
        {% if books.has_next %}
          <div class="page-item"> <a class="page-link" href="{{ url_for('books_app.book_store', page=books.next_num) }}">Next</a></div>
        {% else %}
          <div class="page-item"><a class="page-link btn disabled" href="#">Next</a></div>
        {% endif %}
    </ul>



    </form>
</div>
{% endblock %}

flaskaap/templates/contact.html
{%extends "main_page.html"%}
{%block content%}
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
</head>
<div class="contact">
    <h1>Get in Touch</h1>
    <p>
        If you are interested in working with me or just want to say hi, OR <br>
        Do you have a cool or crazy or great idea that need a web / software <br>
        for its completion? Do not think, just use the below form and send me <br>
        a message / question / suggestion. <br>

        You can directly send me an email at faisal.akhlaq@aol.com <br>
    </p>
    <form class="contact-form">
        <input placeholder="Your Name"><br>
        <input placeholder="Your Email"><br>
        <textarea placeholder="Your Message"></textarea><br>
        <input type="submit" value="Send"><br>
    </form>
    <p><a href="https://www.linkedin.com/in/faisalakhlaq/">My linkedin</a></p>
</div>
{%endblock%}

flaskaap/templates/height.html
{%extends "main_page.html"%}

{% block content %}
    <div class="height_form">
        <h1>Height Survey</h1>
        <div class="error-message">
            {{ error_message | safe }}
        </div>
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <p>
                {{ form.name(size=30, placeholder='Your Name') }}
                {% for error in form.name.errors %}<br>
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </p>
            <p>
                {{ form.height(size=30, placeholder='Your Height in centimeter') }}
                {% for error in form.height.errors %}<br>
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </p>
            <p>
                {{ form.email(size=30, placeholder='Your Email') }}
                {% for error in form.email.errors %}<br>
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>{{ form.submit() }}</p>
        </form>
    </div>
{% endblock %}

flaskaap/templates/login.html
{%extends "main_page.html"%}

{% block content %}
<div class="login-page">
    <h1>Sign In</h1>
    <div class="error-message">
        {{ error_message | safe }}
    </div>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username(size=30, placeholder='Username') }}
            {% for error in form.username.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password(size=30, placeholder='Password') }}
            {% for error in form.password.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>
            {{ form.submit() }}
            <a href="{{url_for('users.request_password_reset')}}">Reset Password</a>
        <a>
    </form>
    <a href="{{url_for('users.register_new_user')}}">Register New User</a>
</div>
{% endblock %}

flaskaap/templates/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <meta charset="UTF-8">
    <title>Python Flask Page</title>
</head>
<body>
    <header>
        <div class="main-menu">
            <div class="container">
                <h1 class="logo">Faisal Akhlaq</h1>
                <strong><nav>
                    <ul class="menu">
                        <li><a href="{{url_for('main.home')}}">Home</a></li>
                        <li><a href="{{url_for('main.about')}}">About</a> </li>
                        <li><a href="{{url_for('main.projects')}}">Projects</a> </li>
                        {% if current_user.is_authenticated %}
                            <li><a href="{{url_for('users.logout')}}">Logout</a></li>
                        {% else %}
                            <li><a href="{{url_for('main.contact')}}">Contact</a></li>
                            <li><a href="{{url_for('users.login')}}">Login</a></li>
                            <li><a href="{{url_for('users.register_new_user')}}">Register</a></li>
                        {% endif %}
                    </ul>
                </nav></strong>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="flash-messages">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                  {{ message }}
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
        {%block content%}{%endblock%}
    </div>
    <div class="main-footer">
        <div>
            Thanks for visiting <br>
            Developed by Faisal Akhlaq
        </div>
        <div>
            Faisal Akhlaq
        </div>
    </div>
</body>
</html>

flaskaap/templates/projects.html
{%extends "main_page.html"%}
{%block content%}
<div class="projects">
    <h1>Projects</h1>
    <a href="{{url_for('users.login')}}">Login Page</a><br>
    <a href="{{url_for('users.account')}}">Account</a><br>
    <a href="{{url_for('users.register_new_user')}}">Register</a><br>
    <a href="{{url_for('books_app.book_admin')}}">Book Store Admin</a><br>
    <a href="{{url_for('books_app.book_store')}}">Book Store</a><br>
    <a href="{{url_for('height_collector.height_data')}}">Height Survey</a><br>
    <a href="https://github.com/faisalakhlaq" target="_blank">Github</a><br>
    <a href="https://gitlab.com/faisal.akhlaq" target="_blank">Gitlab</a><br>
    <a href="https://play.google.com/store/apps/details?id=com.prayerdiary.app" target="_blank">
        Android App: Prayer Diary</a><br>
    <a href=".">Android App: Wutzwhat</a><br>
</div>
<!--&lt;!&ndash;project = []&ndash;&gt;-->
<div class="project-flex-container">
    <div class="img-container">
        <img  class="project-image" src="static/images/register.png">
    </div>
    <div class="description-container">
        <h3>Project Name</h3>
        <h4>Tools used</h4>
        <a href="#">Project link</a>
    </div>
</div>
{% endblock %}

flaskaap/templates/reset_password.html
{%extends "main_page.html"%}

{% block content %}
<div class="login-page">
    <h1>Password Reset</h1>
    <div class="error-message">
        {{ error_message | safe }}
    </div>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.password(size=30, placeholder='Email') }}
            {% for error in form.password.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_password(size=30, placeholder='Email') }}
            {% for error in form.confirm_password.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
</div>
{% endblock %}